### ISSUE TITLE
Why not Binaryen pass?

### ISSUE THREAD

**Issue by mbebenita** [fitzgen/wasm-snip#7]
Do you have any plans for adding a similar feature to https://github.com/WebAssembly/binaryen? I'm curious because it feels that this could have been implemented as a Binaryen pass. Have you looked into that as a possibility? Last I checked, Binaryen didn't have a way to pass arguments to passes (@kripken is that still true), but if that's making it difficult for developers to extend Binaryen we should add that feature.

**Comment by mbebenita** [comment]
Same question for @alexcrichton, re https://github.com/alexcrichton/wasm-gc

**Comment by kripken** [comment]
Snipping could be useful as a Binaryen pass, I think, because it can interact with the optimizer: imagine that you have
```
(func $to-be-snipped
  .. a  big function ..
)

(func $something-else
  .. lots of code ..
  (if (.. condition that never happens ..)
    (call $to-be-snipped)
    .. code that is removable ..
  )
 .. yet more code ..
)
```
If you snip `$to-be-snipped`, then the Binaryen inliner will see it's worth inlining in all the places, since an unreachable node is smaller than a call. And once the unreachable is in `$something-else`, it can remove the code after that unreachable since it is now unreachable too. And that can lead to further inlining and optimizations etc.

However, you would get the same benefits from running the Binaryen optimizer after `wasm-snip`. The only downside is running 2 commands instead of 1, I guess.

Binaryen does have similar things already, like [ExtractFunction](https://github.com/WebAssembly/binaryen/blob/master/src/passes/ExtractFunction.cpp) which removes all the functions but one (helpful to extract a testcase when a bug is hit on one function). There's no way to pass params to passes yet, so we use env vars ;) but that's easily fixed if people care.

**Comment by fitzgen** [comment]
Do you mean re-implement wasm-snip as a binaryen pass? I'm not sure whether that makes sense or not, I'll leave that decision to @kripken, but I have no plans to do that.

Why did I originally implement this in Rust? Because it was easiest for me and the `parity-wasm` crate is pretty great to work with.

**Comment by alexcrichton** [comment]
Ah my experience was basically the same as @fitzgen's. I'm personally *far* more comfortable with Rust than I am with C++, so starting a Rust project using the `parity-wasm` crate was much easier for me than to jump into binaryen's codebase. For us as well it's also much easier for end users to acquire Rust projects through `cargo install` than it is to have them compile C++ code.

Long-term though I'd consider `wasm-gc` a mostly dead CLI tool. I'll keep using it internally in wasm-bindgen but LLD will gain `--gc-sections` natively and I suspect that Binaryen already does the necessary optimizations to replace `wasm-gc`

**Comment by mbebenita** [comment]
> Why did I originally implement this in Rust? Because it was easiest for me and the parity-wasm crate is pretty great to work with.

@fitzgen Yes, that's what I was trying to ask. I think Binaryen would be a more natural home for a pass like this, but I understand how it being written in C++ is blocker. It would however be nice to avoid duplicating efforts with another wasm toolchain written in Rust.

Can we wrap Binaryen in a cargo package with an API that allows Rust programmers to both use and create passes for Binaryen.

**Comment by kripken** [comment]
There are Binaryen bindings for Rust here: https://github.com/pepyakin/binaryen-rs , I've seen people use them for fuzzing wasm from Rust.

**Comment by fitzgen** [comment]
Not sure what else there is to say here. Gonna close this issue down.
