### ISSUE TITLE
error when trying to use it on my project

### ISSUE THREAD

**Issue by jaroslaw-weber** [fitzgen/wasm-snip#8]
I get very weird and long error when trying to use wasm-snip on my project. 
https://github.com/jaroslaw-weber/cbt-diary/tree/master/cbt_diary_wasm
If I replace current build script ( `build.sh` ) to this:
```
echo "building wasm file"
cargo web build
cp target/wasm32-unknown-unknown/release/cbt_diary_wasm.js generated/cbt_diary_wasm.js
cp target/wasm32-unknown-unknown/release/cbt_diary_wasm.wasm generated/cbt_diary_wasm.wasm
wasm-gc generated/cbt_diary_wasm.wasm
wasm-snip generated/cbt_diary_wasm.wasm
wasm-gc generated/cbt_diary_wasm.wasm
wasm-opt generated/cbt_diary_wasm.wasm
```
I get very nasty error.

**Comment by fitzgen** [comment]
Thanks for filing a bug! Are you just running `wasm-snip $wasm_file` without any extra arguments? That isn't going to do anything, you have to tell it which function(s) to snip. It will also write the output wasm (which is the same as the input wasm) to `stdout` since you didn't specify `-o $output_file`. Maybe that is what you are seeing?

Ultimately, you should read the usage so that you have a better idea of what `wasm-snip` does:

```
$ wasm-snip --help
wasm-snip 0.1.3
Nick Fitzgerald <fitzgen@gmail.com>

`wasm-snip` replaces a WebAssembly function's body with an `unreachable`.

Maybe you know that some function will never be called at runtime, but the
compiler can't prove that at compile time? Snip it! Then run `wasm-gc`[0] again
and all the functions it transitively called (which could also never be called
at runtime) will get removed too.

Very helpful when shrinking the size of WebAssembly binaries!

[0]: https://github.com/alexcrichton/wasm-gc

USAGE:
    wasm-snip [FLAGS] [OPTIONS] <input> [--] [function]...

FLAGS:
    -h, --help                        
            Prints help information

        --snip-rust-fmt-code          
            Snip Rust's `std::fmt` and `core::fmt` code.

        --snip-rust-panicking-code    
            Snip Rust's `std::panicking` and `core::panicking` code.

    -V, --version                     
            Prints version information


OPTIONS:
    -o, --output <output>         
            The path to write the output wasm file to. Defaults to stdout.

    -p, --pattern <pattern>...    
            Snip any function that matches the given regular expression.


ARGS:
    <input>          
            The input wasm file containing the function(s) to snip.

    <function>...    
            The specific function(s) to snip. These must match exactly. Use the -p flag for fuzzy matching.
```

and you probably want to run a command something like

```
$ wasm-snip $input_wasm --snip-rust-panicking-code > $output_wasm
```

If you still believe there is a bug in `wasm-snip` after all this, please attach your input `.wasm` file, the exact command you are running, the exact output you see, and a description of what you expected to see instead.

Thanks again!

**Comment by jaroslaw-weber** [comment]
Hey, thanks for help! Yes, I didn't specify output file and I was getting output in the console (can you block this behaviour? It is confusing). I just tried the command without checking the help and assumed it was an error.
It would be nice to have minimal example in README or block default outputting to stdout.
